name: Run Checks on PR to main branch

on:
  pull_request:
    branches:
      main

jobs:
  check-for-secrets:
    uses: ./[Reusable]-Check-for-secrets.yml@main
  
  branch-naming:
    uses: ./[Reusable]-Branch_naming_check_main.yml@main
  
  sonarqube:
    uses: ./[Reusable]-SonarQube_Scan.yml@main

  unit-tests:
    uses: ./[Reusable]-Unit-tests.yml@main
