name: Build & Deploy to Staging

on: 
  pull_request:
      types: 
        - closed
      branches:
         - dev

env:
  ARTIFACT_NAME: StudioGhibliMM-dev
  ARTIFACT_PATH: build-artifact
#  put pipeline variables here

jobs:
  build:
    if: github.event.pull_request.merged == true # Prevents pipeline from running if PR is abandoned etc.
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: Checkout_repository
        uses: actions/checkout@v4
        with:
           fetch-depth: 2
       
       # build - cloudformation yaml (main.yaml?)

       # docker build  
       # docker push 
       
       # task_def.yaml
      
   
    

    
    


      
