name:  Checkmarx 2MS Secret Scanner

on: workflow_call

jobs:
  Check-for-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-Repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 1
      
      - name: Scan-for-Secrets
        run: docker run -v $(pwd):repo checkmarx/2ms:3.6.0 git /repo
