name: Branch Naming Check - Dev

on:
  workflow_call:
        
jobs:
  branch-name-validation:
    runs-on: ubuntu-latest
    steps:
      - name: check-branch-names
        run: |
          dev_regex="^(feature-|Feature-) 
          if [[ ${GITHUB_HEAD_REF} =~ dev-regex]]; then
            echo "Branch naming OK"
          else
            echo "Branch naming does not comply with policy - please prefix feature branch names with "feature-"
            exit 1
          fi
        shell: bash  
      
      
  
