name: SonarQube Scan

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  sonar:
    runs-on: ubuntu-latest
    services:
      sonarqube:
        image: sonarqube:lts
        ports:
          - 9000:9000
        options: --health-cmd="curl --silent --fail http://localhost:9000/api/system/health | grep '\"status\":\"OK\"'" # optional health check
        env:
          SONARQUBE_JDBC_URL: "jdbc:postgresql://localhost/sonar"
          SONARQUBE_JDBC_USERNAME: "sonar"
          SONARQUBE_JDBC_PASSWORD: "sonar"
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Install SonarQube Scanner
        run: |
          curl -sS https://get.sonarqube.org/sonar-scanner-cli-5.0.1.3006-linux.zip -o sonar-scanner.zip
          unzip sonar-scanner.zip
          sudo mv sonar-scanner-*/bin/sonar-scanner /usr/local/bin/
      
      - name: Run SonarQube Scan
        run: |
          sonar-scanner -Dsonar.host.url=http://localhost:9000 -Dsonar.login=${{ secrets.SONAR_TOKEN }}
