name: SonarQube Scan

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  sonar:
    runs-on: ubuntu-latest

    services:
      sonarqube:
        image: sonarqube:lts
        ports:
          - 9000:9000

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run SonarQube Scan
        run: |
          docker run --rm \
            -e SONAR_HOST_URL="http://localhost:9000" \
            -e SONAR_TOKEN="${{ secrets.SONAR_TOKEN }}" \
            sonarsource/sonar-scanner-cli
