name: SonarQube Scan

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  sonar:
    runs-on: ubuntu-latest

    services:
      sonarqube:
        image: sonarqube:lts
        ports:
          - 9000:9000
        options: >-
          --health-cmd "curl -f http://localhost:9000/api/system/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Wait for SonarQube to Start
        run: sleep 60  # Wait for SonarQube to be fully ready

      - name: Run SonarQube Scan
        run: |
          docker run --rm \
            --network=host \
            -e SONAR_HOST_URL="http://localhost:9000" \
            -e SONAR_TOKEN="${{ secrets.SONAR_TOKEN }}" \
            sonarsource/sonar-scanner-cli
